[tool.poetry]
name = "cheetah"
version = "0.1.0"
description = "高速灵活的数据缓存服务"
authors = ["Cheng Qiu <qiucheng@jinniuai.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.5.1"
pyarrow = "^0.17.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
